name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set EC2_HOST environment variable
        run: echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> $GITHUB_ENV

      - name: Debug EC2_HOST
        run: echo "EC2_HOST=$EC2_HOST"

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_HOST <<EOF
            cd /home/ubuntu/nodejs-ec2-deployment || mkdir /home/ubuntu/nodejs-ec2-deployment
            git pull origin main || git clone https://github.com/Narsireddy-1118/nodejs-ec2-deployment.git
            cd nodejs-ec2-deployment
            npm install
            pm2 restart all || pm2 start index.js
          EOF